//     Project: angulate2
// Description: Internally used annotation to add code to the annotations.js file generated by the angulate-sbt plugin.

// Copyright (c) 2016 Johannes.Kastner <jokade@karchedon.de>
//               Distributed under the MIT License (see included LICENSE file)
package angulate2.impl

import scala.annotation.StaticAnnotation

/**
 * Internally used annotation to add code to the annotations.js file generated by the angulate-sbt plugin.
 */
class AngulateAnnotated(annotation: String) extends StaticAnnotation
